# Dell Chromebook 11 3180 / 3189 family.
# ChromeOS board: KEFKA / kefka
# Baseboard / platform lineage: Strago / Intel Braswell
# Firmware assumption: MrChromebox UEFI Full ROM before Yocto boot testing.

require conf/machine/include/intel-braswell-chromebook.inc

MACHINEOVERRIDES =. "kefka:"

MACHINE_DESCRIPTION = "Dell Chromebook 11 3180 KEFKA Braswell Chromebook"
